// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, unnecessary_import, prefer_single_quotes, comment_references, deprecated_member_use_from_same_package
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mQL42qE2lZVN3YhizFACSEWkG0lf5CY',
    appId: '1:573067019829:web:14a0a0940bc42bc24cd37c',
    messagingSenderId: '573067019829',
    projectId: 'fir-project-ca631',
    authDomain: 'fir-project-ca631.firebaseapp.com',
    storageBucket: 'fir-project-ca631.firebasestorage.app',
    measurementId: 'G-86LB9J9H1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo75bm42Ici2aHj42y6xrU1ags2zjlH30',
    appId: '1:573067019829:android:13d23baa09dd82084cd37c',
    messagingSenderId: '573067019829',
    projectId: 'fir-project-ca631',
    storageBucket: 'fir-project-ca631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxuDaSZj6Yw3C1kmIulnPfbGRNfb2qUxM',
    appId: '1:573067019829:ios:1b0611ebc03899524cd37c',
    messagingSenderId: '573067019829',
    projectId: 'fir-project-ca631',
    storageBucket: 'fir-project-ca631.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxuDaSZj6Yw3C1kmIulnPfbGRNfb2qUxM',
    appId: '1:573067019829:ios:1b0611ebc03899524cd37c',
    messagingSenderId: '573067019829',
    projectId: 'fir-project-ca631',
    storageBucket: 'fir-project-ca631.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0mQL42qE2lZVN3YhizFACSEWkG0lf5CY',
    appId: '1:573067019829:web:9defc4b57f57e0fa4cd37c',
    messagingSenderId: '573067019829',
    projectId: 'fir-project-ca631',
    authDomain: 'fir-project-ca631.firebaseapp.com',
    storageBucket: 'fir-project-ca631.firebasestorage.app',
    measurementId: 'G-EXJQY14TBP',
  );
}
